print("Parabéns"+"!"*10)
print("             ")
print("Aqui vai um dinossauro!")
print("             ")
print("                  __")
print("                 / _)")
print("          .-^^^-/ /")
print("       __/       /")
print("      <__.|_|-|_|")
print("             ")
print("E aqui vai um bolo! hummmmmm")
print("             ")
print(" i"*10)
print("#"*21)
print("="*21)
print("#"*21)
print("="*21)
print("#"*21)
